/* Generated By:JavaCC: Do not edit this line. XYZCompilerTreeConstants.java Version 5.0 */
package com.lexAndParse;

public interface XYZCompilerTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMAINCLASS = 1;
  public int JJTCLASSDECL = 2;
  public int JJTVARORMETHODDECL = 3;
  public int JJTMID_VARDECL = 4;
  public int JJTFORMALLIST = 5;
  public int JJTPREDECL = 6;
  public int JJTPOSTDECL = 7;
  public int JJTTYPE = 8;
  public int JJTSTATEMENT = 9;
  public int JJTEXP = 10;
  public int JJTLOWLEVELEXP = 11;
  public int JJTHIGHLEVELEXP = 12;
  public int JJTUNARYEXP = 13;
  public int JJTEXPLIST = 14;
  public int JJTLONG_LITERAL = 15;
  public int JJTINT_LITERAL = 16;
  public int JJTID = 17;
  public int JJTASSIGN = 18;
  public int JJTPRE = 19;
  public int JJTPOST = 20;
  public int JJTINTEGER = 21;
  public int JJTNOT = 22;
  public int JJTAND = 23;
  public int JJTOR = 24;
  public int JJTPLUS = 25;
  public int JJTMINUS = 26;
  public int JJTMULTI = 27;
  public int JJTDIVISION = 28;
  public int JJTLESSTHAN = 29;
  public int JJTLARGERTHAN = 30;
  public int JJTDOT = 31;
  public int JJTLENGTH = 32;
  public int JJTLONG = 33;
  public int JJTBOOLEAN = 34;
  public int JJTCLASS = 35;
  public int JJTSTATIC = 36;
  public int JJTVOID = 37;
  public int JJTMAIN = 38;
  public int JJTEXTENDS = 39;
  public int JJTRETURN = 40;
  public int JJTIF = 41;
  public int JJTELSE = 42;
  public int JJTWHILE = 43;
  public int JJTNEW = 44;
  public int JJTTHIS = 45;
  public int JJTTRUE = 46;
  public int JJTFALSE = 47;


  public String[] jjtNodeName = {
    "Program",
    "MainClass",
    "ClassDecl",
    "VarOrMethodDecl",
    "Mid_VarDecl",
    "FormalList",
    "PreDecl",
    "PostDecl",
    "Type",
    "Statement",
    "Exp",
    "LowLevelExp",
    "HighLevelExp",
    "UnaryExp",
    "ExpList",
    "Long_Literal",
    "Int_Literal",
    "ID",
    "Assign",
    "Pre",
    "Post",
    "Integer",
    "Not",
    "And",
    "Or",
    "Plus",
    "Minus",
    "Multi",
    "Division",
    "Lessthan",
    "Largerthan",
    "Dot",
    "Length",
    "Long",
    "Boolean",
    "Class",
    "Static",
    "Void",
    "Main",
    "Extends",
    "Return",
    "If",
    "Else",
    "While",
    "New",
    "This",
    "True",
    "False",
  };
}
/* JavaCC - OriginalChecksum=6970658adbbcca210b91341293806c8e (do not edit this line) */
